# Generated by Django 3.1.1 on 2020-11-08 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0003_auto_20201108_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='tweet_like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
